EducationPortal/EducationPortal.UI/Controllers/SkillController.cs
using EducationPortal.Domain.Core;
using EducationPortal.Services.Interfaces;
using EducationPortal.UI.Automapper;
using EducationPortal.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EducationPortal.UI.Controllers
{
    [Authorize]
    public class SkillController : Controller
    {
        private readonly ISkillService skillService;
        private readonly IMapper mapper;
        public SkillController(ISkillService skillService, IMapper mapper)
        {
            this.skillService = skillService;
            this.mapper = mapper;
        }

        [HttpGet]
        public IActionResult CreateSkill()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> CreateSkill(SkillVM skillVM)
        {
            if (!(ModelState.IsValid && await skillService.GetUniqueName(skillVM.Name)))
            {
                ModelState.AddModelError("","Invalid name or skill already exists");
                return RedirectToAction("SkillList");
            }
            var mappedSkill = mapper.Map<SkillVM, Skill>(skillVM);
            await skillService.AddSkill(mappedSkill);
            return RedirectToAction("SkillList");
        }

        public IActionResult SkillList()
        {
            return View();
        }
    }
}

EducationPortal/EducationPortal.UI/Controllers/TestController.cs
using AutoMapper;
using EducationPortal.Domain.Core.Entities;
using EducationPortal.Services.Interfaces;
using EducationPortal.UI.Models.TestViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EducationPortal.UI.Controllers
{
    [Authorize]
    public class TestController : Controller
    {
        private readonly ILogger<TestController> logger;
        private readonly ICourseTestService testService;
        private readonly IMapper mapper;

        public TestController(ILogger<TestController> logger, ICourseTestService testService, IMapper mapper)
        {
            this.logger = logger;
            this.testService = testService;
            this.mapper = mapper;
        }

        [HttpGet]
        public IActionResult CreateTest()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateTest(TestVM testVM)
        {
            if (!(ModelState.IsValid && await testService.UniqueTestName(testVM.Name)))
            {
                return View("CreateTest", testVM);
            }

            var mapped = mapper.Map<TestVM, Test>(testVM);
            await testService.AddTest(mapped);
            return RedirectToAction("CreateCourse", "Course");
        }
    }
}

EducationPortal/EducationPortal.UI/Views/Skill/CreateSkill.cshtml
@model EducationPortal.UI.Models.SkillVM



<div class="col-sm-2">
    <h4 class="skillColor">Add Skill</h4>
    <form asp-action="CreateSkill">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <input asp-for="Name" class="form-control" placeholder="skill name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Add Skill" class="btn btn-outline-light" />
        </div>
    </form>
</div>

EducationPortal/EducationPortal.UI/Views/Skill/SkillList.cshtml
@model EducationPortal.UI.Models.SkillVM

@inject EducationPortal.Services.Interfaces.ISkillService Skill

@{
    ViewData["Title"] = "Skills List";
}

@{
    Layout = "_Layout";
}
<h3 class="materialsColor books">Skills list</h3>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div style="float:right"> @Html.ActionLink("I WILL USE EXISTING SKILLS", "CreateTest", "Test", null, new { @class = "linkDecor btn btn-outline-light", @style = "margin-left:20px;" })</div>

<div class="row" style="margin-top:5%; margin-bottom:5%; ">
    <div class="col-md-4 textCenter">
        <dl>
            <dt class="skillColor paragraphColor">Existing skills</dt>
            @foreach (var skill in Skill.GetSkills())
            {
                <dd class="skillColor">@skill.Name</dd>
            }
        </dl>
    </div>
    @{await Html.RenderPartialAsync("CreateSkill", Model); }

</div>


<script src="~/js/skillList.js" asp-append-version="true"></script>