EducationPortal/EducationPortal.UI/Controllers/MaterialController.cs
using EducationPortal.Domain.Core;
using EducationPortal.Services.Interfaces;
using EducationPortal.UI.Automapper;
using EducationPortal.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EducationPortal.UI.Controllers
{
    [Authorize]

    public class MaterialController : Controller
    {
        private readonly ILogger<MaterialController> logger;
        private readonly IMaterialService materialService;
        private readonly IVideoMaterialService videoMaterialService;
        private readonly IBookMaterialService bookMaterialService;
        private readonly IArticleMaterialService articleMaterialService;
        private readonly IMapper mapper;

        public MaterialController(ILogger<MaterialController> logger, IMaterialService materialService, IVideoMaterialService videoMaterialService, IBookMaterialService bookMaterialService, IArticleMaterialService articleMaterialService, IMapper mapper)
        {
            this.logger = logger;
            this.mapper = mapper;
            this.materialService = materialService;
            this.bookMaterialService = bookMaterialService;
            this.videoMaterialService = videoMaterialService;
            this.articleMaterialService = articleMaterialService;
        }

        [HttpGet]
        public IActionResult MaterialList()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateVideo()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateVideo(VideoMaterialVM videoMaterialVM)
        {
            if (!ModelState.IsValid && await materialService.UniqueMaterialName(videoMaterialVM.Name))
            {
                return View("CreateVideo", videoMaterialVM);
            }

            var mappedVideo = mapper.Map<VideoMaterialVM, VideoMaterial>(videoMaterialVM);

            await videoMaterialService.AddVideoMaterial(mappedVideo);
            return RedirectToAction("MaterialList", "Material");
        }

        [HttpGet]
        public IActionResult CreateArticle()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateArticle(ArticleMaterialVM articleMaterialVM)
        {
            if (!ModelState.IsValid && await materialService.UniqueMaterialName(articleMaterialVM.Name))
            {
                return View("CreateArticle", articleMaterialVM);
            }

            var mappedArticle = mapper.Map<ArticleMaterialVM, ArticleMaterial>(articleMaterialVM);

            await articleMaterialService.AddArticleMaterial(mappedArticle); 
            return RedirectToAction("MaterialList", "Material");

        }

        [HttpGet]
        public IActionResult CreateBook()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateBook(BookMaterialVM bookMaterialVM)
        {
            if (!ModelState.IsValid && await materialService.UniqueMaterialName(bookMaterialVM.Name))
            {
                return View("CreateBook", bookMaterialVM);
            }

            var mappedBook = mapper.Map<BookMaterialVM, BookMaterial>(bookMaterialVM);

            await bookMaterialService.AddBookMaterial(mappedBook);
            return RedirectToAction("MaterialList", "Material");
        }
    }
}

EducationPortal/EducationPortal.UI/Controllers/SkillController.cs
using EducationPortal.Domain.Core;
using EducationPortal.Services.Interfaces;
using EducationPortal.UI.Automapper;
using EducationPortal.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EducationPortal.UI.Controllers
{
    [Authorize]
    public class SkillController : Controller
    {
        private readonly ISkillService skillService;
        private readonly IMapper mapper;
        public SkillController(ISkillService skillService, IMapper mapper)
        {
            this.skillService = skillService;
            this.mapper = mapper;
        }

        [HttpGet]
        public IActionResult CreateSkill()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> CreateSkill(SkillVM skillVM)
        {
            if (!(ModelState.IsValid && await skillService.GetUniqueName(skillVM.Name)))
            {
                ModelState.AddModelError("","Invalid name or skill already exists");
                return RedirectToAction("SkillList");
            }
            var mappedSkill = mapper.Map<SkillVM, Skill>(skillVM);
            await skillService.AddSkill(mappedSkill);
            return RedirectToAction("SkillList");
        }

        public IActionResult SkillList()
        {
            return View();
        }
    }
}

EducationPortal/EducationPortal.UI/Views/Material/CreateArticle.cshtml
@model EducationPortal.UI.Models.ArticleMaterialVM

@{
    ViewData["Title"] = "Add Article";
}
@{
    Layout = "_Layout";
}
<div class="clsd">
    <h1 class="mainWordA">Add Article</h1>
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateArticle">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label backgroundcolor"></label>
                <input asp-for="Name" class="form-control inputColorA" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Resource" class="control-label backgroundcolor"></label>
                <input asp-for="Resource" class="form-control inputColorA" />
                <span asp-validation-for="Resource" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishDate" class="control-label backgroundcolor"></label>
                <input asp-for="PublishDate" class="form-control inputColorA" />
                <span asp-validation-for="PublishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add Article" class="btn btn-outline-light" />
            </div>

        </form>
    </div>
</div>
<script src="~/js/article.js" asp-append-version="true"></script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EducationPortal/EducationPortal.UI/Views/Material/CreateBook.cshtml
@model EducationPortal.UI.Models.BookMaterialVM

@{
    ViewData["Title"] = "Add Book";
}
@{ 
    Layout = "_Layout";
}

<h1 class="mainWordB">Add Book</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateBook">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label backgroundcolor"></label>
                <input asp-for="Name" class="form-control inputcolorB" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Author" class="control-label backgroundcolor"></label>
                <input asp-for="Author" class="form-control inputcolorB" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pages" class="control-label backgroundcolor"></label>
                <input asp-for="Pages" class="form-control inputcolorB" />
                <span asp-validation-for="Pages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearOfPublish" class="control-label backgroundcolor"></label>
                <input asp-for="YearOfPublish" class="form-control inputcolorB" />
                <span asp-validation-for="YearOfPublish" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Format" class="control-label backgroundcolor"></label>
                @Html.DropDownListFor(Model => Model.Format, Html.GetEnumSelectList(typeof(BookFormatVM)))
                <span asp-validation-for="Format" class="text-danger"></span>
                <input type="submit" value="Add Book" class="btn btn-outline-light cls" />
            </div>
        </form>
    </div>
</div>
<script src="~/js/book.js" asp-append-version="true"></script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EducationPortal/EducationPortal.UI/Views/Material/CreateVideo.cshtml
@model EducationPortal.UI.Models.VideoMaterialVM

@{
    ViewData["Title"] = "Add Video";
}
@{
    Layout = "_Layout";
}
<h1 class="mainWordV">Add Video</h1>

<hr />
<div class="row ">
    <div class="col-md-4">
        <form asp-action="CreateVideo">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label backgroundcolor"></label>
                <input asp-for="Name" class="form-control inputColorV" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label backgroundcolor"></label>
                <input asp-for="Duration" class="form-control inputColorV" placeholder="00,00" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Link" class="control-label backgroundcolor"></label>
                <input asp-for="Link" class="form-control inputColorV" placeholder="https://..." />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quality" class="control-label backgroundcolor"></label>
                @Html.DropDownListFor(Model => Model.Quality, Html.GetEnumSelectList(typeof(VideoQualityVM)))
                <span asp-validation-for="Quality" class="text-danger"></span>
                <input type="submit" value="Add Video" class="btn btn-outline-info cls" />
            </div>
        </form>
    </div>
</div>
<script src="~/js/video.js" asp-append-version="true"></script>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EducationPortal/EducationPortal.UI/Views/Material/MaterialList.cshtml
@inject EducationPortal.Services.Interfaces.IMaterialService Material

@{
    ViewData["Title"] = "Existing Materials";
}
@{
    Layout = "_Layout";
}
<div class="materialList">
    <h3 class="materialsColor books">Materials list</h3>
</div>
<div class="row">
    <div class="col-md-4 align-self-start textCenter">
        <dl>
            <dt class="paragraphColor books">Videos</dt>
            @foreach (var video in Material.GetVideoMaterials())
            {
                <dd class="materialsColor books"> @video.Name</dd>
            }
            <div>@Html.ActionLink("Add new video", "CreateVideo", "Material", null, new { @class = "linkDecor btn btn-info" })</div>
        </dl>
    </div>
    <div class="col-md-4 align-self-center textCenter">
        <dl>
            <dt class="paragraphColor books">Articles</dt>
            @foreach (var article in Material.GetArticleMaterials())
            {
                <dd class="materialsColor books"> @article.Name</dd>
            }
            <div>@Html.ActionLink("Add new article", "CreateArticle", "Material", null, new { @class = "linkDecor btn btn-info" })</div>
        </dl>
    </div>
    <div class="col-md-4 align-self-end textCenter">
        <dl>
            <dt class="paragraphColor books">Books</dt>
            @foreach (var book in Material.GetBookMaterials())
            {
                <dd class="materialsColor books">@book.Name</dd>
            }
            <div>@Html.ActionLink("Add new book", "CreateBook", "Material", null, new { @class = "linkDecor btn btn-info" })</div>
        </dl>
    </div>
</div>
<div class=" materialList"> @Html.ActionLink("I WILL USE EXISTING MATERIALS", "SkillList", "Skill", null, new { @class = "linkDecor btn btn-outline-dark", @style = "margin-left:20px; color: white;" })</div>
<script src="~/js/materialList.js" asp-append-version="true"></script>